"""empty message

Revision ID: 193392e044c8
Revises: 129b2a2ed050
Create Date: 2025-05-20 20:01:57.888361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193392e044c8'
down_revision = '129b2a2ed050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
