"""empty message

Revision ID: 489aa13644ba
Revises: 596f4ed782a8
Create Date: 2025-05-24 03:13:20.441597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489aa13644ba'
down_revision = '596f4ed782a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firsttime', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.drop_column('firsttime')

    # ### end Alembic commands ###
