"""empty message

Revision ID: 6c58c656bacf
Revises: 193392e044c8
Create Date: 2025-05-21 21:55:31.507883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c58c656bacf'
down_revision = '193392e044c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('targetleetcode', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('targetproject', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('targetproject')
        batch_op.drop_column('targetleetcode')

    # ### end Alembic commands ###
