"""empty message

Revision ID: 7d95ff5bc4de
Revises: 82c4e1ff568b
Create Date: 2025-05-22 14:21:44.775875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d95ff5bc4de'
down_revision = '82c4e1ff568b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('targetleetcode', sa.Integer(), nullable=True),
    sa.Column('targetproject', sa.Integer(), nullable=True),
    sa.Column('targetdate', sa.Date(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('targetleetcode')
        batch_op.drop_column('targetproject')
        batch_op.drop_column('progressleetcode')
        batch_op.drop_column('targetdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('targetdate', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('progressleetcode', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('targetproject', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('targetleetcode', sa.INTEGER(), nullable=True))

    op.drop_table('target')
    # ### end Alembic commands ###
