"""empty message

Revision ID: a35953628a34
Revises: 7d95ff5bc4de
Create Date: 2025-05-23 08:47:30.025769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35953628a34'
down_revision = '7d95ff5bc4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currentleetcode', sa.Integer(), nullable=True),
    sa.Column('currentproject', sa.Integer(), nullable=True),
    sa.Column('currentinterview', sa.Integer(), nullable=True),
    sa.Column('resume', sa.Boolean(), nullable=True),
    sa.Column('bq', sa.Boolean(), nullable=True),
    sa.Column('tq', sa.Boolean(), nullable=True),
    sa.Column('mock', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current')
    # ### end Alembic commands ###
